### ISSUE TITLE
Question about FairKL

### ISSUE THREAD

**Issue by xvolcano02** [EIDOSLAB/unbiased-contrastive-learning#2]
Recently, I have been trying to implement FairKL on my own, but I don't quite understand how to sample positive bias-aligned and bias-conflicting according to the paper. Can you explain how to implement FairKL in a batch based on this formula?

**Comment by carloalbertobarbano** [comment]
Positive bias-aligned are the samples of the same class which also share the same bias with respect to the anchor, while positive bias-conflicting have a different bias.  In supervised debiasing datasets (i.e. biased-mnist) you have a label indicating the bias for each sample. 

Given a minibatch `(z, labels, bias_labels)`, you can compute the positive, bias-aligned and bias-conflicting masks as: 

```python
labels = labels.view(-1, 1)
positive_mask = torch.eq(labels, labels.T)

bias_labels = bias_labels.view(-1, 1)
aligned_mask = torch.eq(bias_labels, bias_labels.T)

conflicting_mask = ~aligned_mask
``` 

By combining the masks together you can select the samples you want in the batch (i.e. positive bias-aligned as `pos_aligned = positive_mask * aligned_mask`)

The reasoning is similar to what's done here https://github.com/HobbitLong/SupContrast/blob/master/losses.py

**Comment by xvolcano02** [comment]
thank you very much!
